blank_issues_enabled: false
contact_links:
  - name: Team Discussion
    url: https://github.com/ShadiiAM/SOEN390-Project-W26/discussions
    about: Use discussions for questions and general conversations
